Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/custom_facts/util/values.rb'
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/core/execution/windows.rb'
    - 'lib/custom_facts/core/execution/base.rb'
    - 'lib/custom_facts/util/windows/error.rb'

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /(?:(?!.+_spec.rb).)*$/
Style/ClassVars:
  Exclude:
    - !ruby/regexp /(?:(?!.+_resolver.rb).)*$/
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'spec/mocks/**/*'
    - 'lib/custom_facts/util/windows/process.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/custom_facts/util/parser_spec.rb'
    - 'spec/custom_facts/core/logging_spec.rb'
    - 'lib/custom_facts/util/values.rb'
    - 'lib/custom_facts/util/loader.rb'
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/core/execution/windows.rb'
    - 'lib/custom_facts/core/execution/base.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/custom_facts/util/normalization_spec.rb'
    - 'spec/custom_facts/shared_contexts/platform.rb'
    - 'spec/custom_facts/core/execution/windows_spec.rb'
    - 'spec/custom_facts/core/execution/posix_spec.rb'
    - 'lib/custom_facts/util/resolution.rb'
    - 'lib/custom_facts/core/execution/windows.rb'
    - 'lib/custom_facts/core/execution/posix.rb'

Style/CaseEquality:
  Exclude:
    - 'spec/custom_facts/util/confine_spec.rb'
    - 'lib/custom_facts/util/confine.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/custom_facts/util/values.rb'
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/core/execution/windows.rb'
    - 'lib/custom_facts/core/execution/posix.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/custom_facts/util/values.rb'
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/core/execution/windows.rb'
    - 'lib/custom_facts/core/execution/posix.rb'

Lint/RescueException:
  Exclude:
    - 'lib/custom_facts/util/parser.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/custom_facts/util/fact.rb'

Style/DoubleNegation:
  Exclude:
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/util/confine.rb'
    - 'lib/custom_facts/core/execution/windows.rb'
    - 'lib/custom_facts/core/execution/posix.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/custom_facts/core/suitable.rb'

Style/StderrPuts:
  Exclude:
    - 'lib/custom_facts/core/logging.rb'

Style/ModuleFunction:
  Exclude:
    - 'lib/custom_facts/core/logging.rb'

Naming/MethodName:
  Exclude:
    - 'spec/mocks/**/*'

Naming/PredicateName:
  Exclude:
    - 'lib/custom_facts/core/suitable.rb'

Style/MethodMissingSuper:
  Exclude:
    - 'lib/facter-ng.rb'

Style/MissingRespondToMissing:
  Exclude:
    - 'lib/facter-ng.rb'

Naming/FileName:
  Exclude:
    - 'lib/facter-ng.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/custom_facts/util/windows/user.rb'
    - 'lib/custom_facts/util/windows/process.rb'

Naming/VariableName:
  Exclude:
    - 'lib/custom_facts/util/windows/error.rb'
    - 'lib/custom_facts/util/windows/process.rb'
