sudo: false
language: ruby
cache:
  bundler: true
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
matrix:
  include:
    - rvm: 2.6
      script:
        - bundle exec rubocop
        - bundle exec rubycritic --no-browser -s 80 -f console
        - bundle exec rake spec

    - rvm: 2.5
      script:
        - bundle exec rake spec

    - rvm: 2.4
      script:
        - bundle exec rake spec

    - rvm: 2.3
      script:
        - bundle exec rake spec

    - rvm: jruby-head
      script:
        - bundle exec rake spec

