language: ruby
sudo: false
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
notifications:
  email: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
git:
  depth: false
